export const HeliosColors = {
  background: '#141414',
  backgroundStripe: '#222222',
  surface: '#1E1E1E',
  cardLight: '#F2EFEA',
  cardBorder: '#E5E1DC',
  accent: '#A8FF00',
  accentDim: 'rgba(168,255,0,0.12)',
  textPrimary: '#FFFFFF',
  textSecondary: '#777777',
  textOnCard: '#1A1A1A',
  textOnCardMuted: '#666666',
  heartRed: '#FF3B30',
  sleepDeep: '#6D28D9',
  sleepLight: '#C4B5FD',
  sleepREM: '#8B5CF6',
  wakeOrange: '#FF9500',
  lineSubtle: '#333333',
  lineOnCard: '#D0CCC7',
  transparent: 'transparent',
  recoveryGreen: '#00D26A',
  recoveryYellow: '#FFD60A',
  recoveryRed: '#FF453A',
  strainLight: '#4CC9F0',
  strainModerate: '#A8FF00',
  strainHigh: '#FF9500',
  strainAllOut: '#FF3B30',
} as const;

export const HeliosFonts = {
  display: 'BebasNeue-Regular',
  mono: 'IBMPlexMono-Medium',
  monoRegular: 'IBMPlexMono-Regular',
  body: 'DMSans-Variable',
  script: 'Caveat-Variable',
} as const;

export const HeliosTypography = {
  heroTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 48,
    lineHeight: 50,
    letterSpacing: 1,
  },
  sectionTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 32,
    lineHeight: 36,
    letterSpacing: 0.5,
  },
  cardTitle: {
    fontFamily: 'BebasNeue-Regular',
    fontSize: 22,
    lineHeight: 26,
    letterSpacing: 0.5,
  },
  metricLarge: {
    fontFamily: 'IBMPlexMono-Medium',
    fontSize: 36,
    lineHeight: 40,
    fontVariant: ['tabular-nums'] as ('tabular-nums')[],
  },
  metricMedium: {
    fontFamily: 'IBMPlexMono-Medium',
    fontSize: 24,
    lineHeight: 28,
    fontVariant: ['tabular-nums'] as ('tabular-nums')[],
  },
  metricSmall: {
    fontFamily: 'IBMPlexMono-Medium',
    fontSize: 14,
    lineHeight: 18,
    fontVariant: ['tabular-nums'] as ('tabular-nums')[],
  },
  label: {
    fontFamily: 'IBMPlexMono-Medium',
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1.5,
    textTransform: 'uppercase' as const,
  },
  body: {
    fontFamily: 'DMSans-Variable',
    fontSize: 15,
    lineHeight: 22,
  },
  bodySmall: {
    fontFamily: 'DMSans-Variable',
    fontSize: 13,
    lineHeight: 18,
  },
  script: {
    fontFamily: 'Caveat-Variable',
    fontSize: 28,
    lineHeight: 32,
  },
} as const;

export const HeliosSpacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
  screenPadding: 20,
  cardPadding: 16,
  cardRadius: 16,
  cardGap: 12,
} as const;
